import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./ui/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="absolute top-0 p-5 z-50 bg-transparent flex justify-between w-full">
          <h1>
            <span className="p-1 bg-red-700 rounded-full px-1">Yu</span> Barbell
          </h1>
          <Navbar />
        </header>
        <main className="flex flex-col items-center justify-center bg-black">
          {children}
        </main>
      </body>
    </html>
  );
}
