import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./ui/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <header className="sticky top-0 z-50 bg-transparent flex justify-between">
          <h1>
            <span>Yu</span> Barbell
          </h1>
          <Navbar />
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}
